
server:
  port: 5555

spring:
  application:
    name: timesheet-page
  cloud:
    loadbalancer:
      retry:
        enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

timesheet:
  rest:
    url: http://timesheet-rest:12345